name: Publish to Registries

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Sync Python project
        run: uv sync --frozen
        working-directory: python
      - name: Run Python tests
        run: uv run pytest tests/*
        working-directory: python

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install and Test JS/TS
        run: |
          npm install
          npm test --workspaces --if-present

  publish-python:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build and Publish Python
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_API_TOKEN }}
        working-directory: python

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      - run: npm install

      - run: npm run build
        working-directory: typescript
      - run: npm run build
        working-directory: react

      - run: npm publish --access public --provenance
        working-directory: typescript
      - run: npm publish --access public --provenance
        working-directory: react
